[project]
name = "rodep-lore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "sphinx>=9.0.4",
    "sphinx-rtd-theme>=0.5.1",
]
