[project]
name = "rodep-lore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.12"
dependencies = [
    "myst-parser>=4.0.1",
    "sphinx>=6,<8",
    "sphinx-rtd-theme>=0.5.1",
]
