- name: 依存パッケージをインストール
  ansible.builtin.apt:
    name: [ca-certificates, curl, gnupg, git, apt-utils]
    state: present
    update_cache: yes

- name: GPGキー保存用ディレクトリ作成
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Docker公式GPGキーを取得
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Dockerリポジトリを追加
  ansible.builtin.apt_repository:
    # x86_64 を amd64 に置換するプロの技
    repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    filename: docker

- name: Docker Engine一式をインストール
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
    # コンテナ内でのエラーを避けるため、起動を抑制する
    policy_rc_d: 101
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Dockerサービスの状態管理
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  # テストコンテナ環境（localhost）ならエラーを無視する
  ignore_errors: "{{ inventory_hostname == 'localhost' }}"

- name: ユーザーをdockerグループに追加
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: DockerのストレージドライバーをVFSに設定 (テスト環境用)
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "storage-driver": "vfs"
      }
  # localhost（テストコンテナ）の時だけ実行する
  when: inventory_hostname == 'localhost'
  register: docker_config

- name: Dockerサービスを再起動 (設定変更時のみ)
  ansible.builtin.shell: service docker restart
  when: 
    - inventory_hostname == 'localhost'
    - docker_config.changed

- name: DockerのストレージドライバーとDNSを設定 (テスト環境用)
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "storage-driver": "vfs",
        "dns": ["8.8.8.8", "8.8.4.4"]
        "build-network": "host"
      }
  when: inventory_hostname == 'localhost'
  register: docker_config
